development:
  RIDEPILOT_HOST: 188.166.227.111
  SYSTEM_ADMIN_EMAIL: siya.ny01@gmail.com
  SYSTEM_ADMIN_PASSWORD: Siya01051995
  SYSTEM_SEND_FROM_ADDRESS: siya.ny01@gmail.com
  OPEN_TRIP_PLANNER_URL: nil
  GOOGLE_API_KEY: AIzaSyDWOlFUXc4fJkmqrxYn3IOWZa4TeDhyhZ8

test:
  RIDEPILOT_HOST:
  SYSTEM_SEND_FROM_ADDRESS: test@example.com
  OPEN_TRIP_PLANNER_URL:

production:
  RIDEPILOT_HOST: 188.166.227.111
  SYSTEM_ADMIN_EMAIL: siya.ny01@gmail.com
  SYSTEM_ADMIN_PASSWORD: Siya01051995
  SMTP_MAIL_ADDR: nil
  SMTP_MAIL_DOMAIN: nil
  SMTP_MAIL_PASSWORD: nil
  SMTP_MAIL_PORT: nil
  SMTP_MAIL_USER_NAME: nil
  SYSTEM_SEND_FROM_ADDRESS: siya.ny01@gmail.com
  OPEN_TRIP_PLANNER_URL: nil
  GOOGLE_API_KEY: AIzaSyDWOlFUXc4fJkmqrxYn3IOWZa4TeDhyhZ8
