development:
  adapter:  postgis
  encoding: unicode
  database: ridepilot_development
  username: siyany
  schema_search_path: public

test: &test
  adapter:  postgis
  encoding: unicode
  database: ridepilot_test
  username: siyany

production:
  adapter:  postgis
  encoding: unicode
  pool: 25
  timeout: 5000
  database: ridepilot
  username: deployer
  password: ridepilot
